### ISSUE TITLE
Use github Actions

### ISSUE THREAD

**Issue by Xnkr** [Shernz/Upskilling#7]
Use github actions to automatically run unit tests when code is pushed.

**Comment by Shernz** [comment]
Pushed to any branch or main?

**Comment by Xnkr** [comment]
I don't know. I've never used it before. I'm thinking any branch?

**Comment by Xnkr** [comment]
You should close out issues once you're done with them.

Or link the PR to the issue so it gets auto resolved when PR is merged.
